package constants

var CHILD_DEFAULT_ACCESS = map[float64]string{
	102: "UPDATE_SFM_DETAILS",
	103: "VIEW_SFM_DETAILS",
	105: "ADD_SFM_HEALTH_RECORD",
	106: "VIEW_SFM_HEALTH_RECORD",
	107: "ADD_SFM_HEALTH_RECORD_METADATA",
	108: "VIEW_SFM_HEALTH_RECORD_METADATA",
	109: "SUGGEST_SFM_HEALTH_RECORD_METADATA",
}

var HEAD_DEFAULT_ACCESS = map[float64]string{
	101: "ADD_SFM",
	102: "UPDATE_SFM_DETAILS",
	103: "UPDATE_SFM_ACCESS",
	104: "VIEW_SFM_DETAILS",
	105: "VIEW_SFM_ACCESS",
	106: "DELETE_SFM",
	107: "ADD_SFM_HEALTH_RECORD",
	108: "VIEW_SFM_HEALTH_RECORD",
	109: "ADD_SFM_HEALTH_RECORD_METADATA",
	110: "VIEW_SFM_HEALTH_RECORD_METADATA",
	111: "SUGGEST_SFM_HEALTH_RECORD_METADATA",
}
